ARG PHP_EXTENSIONS="apcu opcache pdo_mysql"
FROM thecodingmachine/php:7.2-v2-slim-apache
# The build will automatically trigger the download and compilation
# of the extensions (thanks to a ONBUILD hook in the slim image)

# Change back Apache user and group to www-data
# ENV APACHE_RUN_USER=www-data \
#     APACHE_RUN_GROUP=www-data